# Change these first
owner: SpookyKipper # Your GitHub organization or username, where this repository lives
repo: SpookhostStatusPage # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
 # cname: demo.upptime.js.org
  baseUrl: /SpookhostStatusPage
  logoUrl: https://clear-status-spookykip.vercel.app/images/spookhost.svg
  name: Spookhost Service Status
  introTitle: "Spookhost Service Status"
  introMessage: This status page provides updated information about **Spookhost**'s systems normal operation and incidents that may happen.
  navbar:
  #  - title: Status
   #   href: /
   # - title: GitHub
    #  href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
