# Change these first
owner: SpookyKipper # Your GitHub organization or username, where this repository lives
repo: SpookhostStatusPage # The name of this repository

sites:
#Start Core Services
  - name: Client Area
    url: https://app.spookhost.eu.org
  - name: cPanel
    url: https://cpanel.spookhost.eu.org
  - name: Online File Manager
    url: https://files.spookhost.eu.org/new
  - name: FTP Server
    url: ftpupload.net
    check: "tcp-ping"
    port: 21
  - name: Nameserver 1
    url: ns1.spookhost.eu.org
    expectedStatusCodes:
      - 0
  - name: Nameserver 2
    url: ns2.spookhost.eu.org
    check: "ping"
    expectedStatusCodes:
      - 0
    #Start Traige Services
  - name: phpMyAdmin
    url: 185.27.134.10
    check: "tcp-ping"
  - name: Softaculous
    url: sv1.scriptinstall.rocks
    check: "tcp-ping"
    port: 2083
#Start Others
  - name: Homepage
    url: https://spookhost.eu.org/
  - name: Forum
    url: https://forum.spookhost.eu.org/

  #- name: Online File Manager
   # url: https://files.spookhost.eu.org/new
    
    
   

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
 # cname: demo.upptime.js.org
  baseUrl: /SpookhostStatusPage
  logoUrl: https://clear-status-spookykip.vercel.app/images/spookhost.svg
  name: Spookhost Service Status
  introTitle: "Spookhost Service Status"
  introMessage: This status page provides updated information about **Spookhost**'s systems normal operation and incidents that may happen.
  themeUrl: https://spookykipper.github.io/AssetsWebsite/Spookhost/Upptime/theme.css
  favicon: https://clear-status-spookykip.vercel.app/images/spookhost.svg
  faviconSvg: https://clear-status-spookykip.vercel.app/images/spookhost.svg
  customBodyHtml: "<script src='https://spookykipper.github.io/AssetsWebsite/Spookhost/Upptime/groups.js'></script>"  
  navbar:
  #  - title: Status
   #   href: /
   # - title: GitHub
    #  href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

i18n:
  footer: © Copyright 2022 Spookhost
  allSystemsOperational: All Systems Operational
