# Change these first
owner: SpookyKipper # Your GitHub organization or username, where this repository lives
repo: SpookhostStatusPage # The name of this repository

sites:
  - name: Client Area
    url: https://app.spookhost.eu.org
  - name: cPanel
    url: https://cpanel.spookhost.eu.org
  - name: Online File Manager
    url: https://files.spookhost.eu.org/new
  - name: FTP Server
    url: ftpupload.net
    check: "tcp-ping"
    port: 21
 # - name: FTP Server
  #  url: https://cpanel.spookhost.eu.org
  #- name: Online File Manager
 #   url: https://app.spookhost.eu.org
  #- name: cPanel
   # url: https://cpanel.spookhost.eu.org
  #- name: Online File Manager
   # url: https://files.spookhost.eu.org/new
  #- name: Client Area
  #  url: https://app.spookhost.eu.org
 # - name: cPanel
  #  url: https://cpanel.spookhost.eu.org
  #- name: Online File Manager
   # url: https://files.spookhost.eu.org/new
    
    
   

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
 # cname: demo.upptime.js.org
  baseUrl: /SpookhostStatusPage
  logoUrl: https://clear-status-spookykip.vercel.app/images/spookhost.svg
  name: Spookhost Service Status
  introTitle: "Spookhost Service Status"
  introMessage: This status page provides updated information about **Spookhost**'s systems normal operation and incidents that may happen.
  themeUrl: https://spookykipper.github.io/SpookhostStatusPage/theme.css
  navbar:
  #  - title: Status
   #   href: /
   # - title: GitHub
    #  href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
